package dev.sbomscope.sbom;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import org.junit.jupiter.api.Test;
import tools.jackson.databind.ObjectMapper;

import dev.sbomscope.sbom.ParsedSbom.ParsedComponent;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Parser tests run against SBOMs generated by the real tools SBOMscope targets — the
 * CycloneDX Maven plugin and npm's own generator — rather than hand-written samples,
 * so they exercise the quirks those tools actually emit.
 */
class CycloneDxParserTest {

    private final CycloneDxParser parser = new CycloneDxParser(new ObjectMapper());

    private InputStream fixture(String name) {
        InputStream stream = getClass().getResourceAsStream("/sboms/" + name);
        assertThat(stream).as("fixture %s should exist", name).isNotNull();
        return stream;
    }

    private InputStream json(String content) {
        return new ByteArrayInputStream(content.getBytes(StandardCharsets.UTF_8));
    }

    @Test
    void parsesMavenGeneratedSbom() {
        ParsedSbom sbom = parser.parse(fixture("maven-sbomscope.cdx.json"));

        assertThat(sbom.specVersion()).isEqualTo("1.6");
        assertThat(sbom.components()).isNotEmpty();
        assertThat(sbom.edges()).isNotEmpty();
        assertThat(sbom.rootBomRef()).isNotBlank();

        // Maven coordinates should survive intact, since they drive both the registry
        // links in the export and the purl used for vulnerability lookups.
        assertThat(sbom.components())
                .anySatisfy(component -> {
                    assertThat(component.group()).isNotNull();
                    assertThat(component.purl()).startsWith("pkg:maven/");
                });
    }

    @Test
    void parsesNpmGeneratedSbom() {
        ParsedSbom sbom = parser.parse(fixture("npm-frontend.cdx.json"));

        assertThat(sbom.specVersion()).isEqualTo("1.5");
        assertThat(sbom.components()).isNotEmpty();
        assertThat(sbom.components())
                .anySatisfy(component -> assertThat(component.purl()).startsWith("pkg:npm/"));
    }

    @Test
    void marksExactlyOneRootComponent() {
        ParsedSbom sbom = parser.parse(fixture("maven-sbomscope.cdx.json"));

        assertThat(sbom.components().stream().filter(ParsedComponent::root))
                .hasSize(1);
    }

    @Test
    void classifiesTheProjectsOwnModulesAsApplicationCode() {
        // The aggregate BOM's root is the parent pom, and the only things it depends on
        // directly are sbomscope-frontend and sbomscope-backend — the project's own modules.
        // Calling those "direct dependencies" made every genuinely declared dependency look
        // transitive and offered the user two rows they cannot upgrade.
        ParsedSbom sbom = parser.parse(fixture("maven-sbomscope.cdx.json"));

        assertThat(sbom.components())
                .filteredOn(component -> component.scope() == DependencyScope.APPLICATION)
                .extracting(ParsedComponent::name)
                .containsExactlyInAnyOrder("sbomscope-parent", "sbomscope-frontend", "sbomscope-backend");
    }

    @Test
    void treatsWhatTheModulesDeclareAsDirect() {
        ParsedSbom sbom = parser.parse(fixture("maven-sbomscope.cdx.json"));

        // Exactly what the backend module's pom declares. The module lists seven
        // dependencies, and the seventh is sbomscope-frontend — a sibling module, so it stays
        // application code rather than becoming a dependency the user is invited to upgrade.
        // That exclusion is the rule "neighbours of the application set, minus the set" doing
        // the work the old boolean could not.
        assertThat(sbom.components())
                .filteredOn(component -> component.scope() == DependencyScope.DIRECT)
                .extracting(ParsedComponent::name)
                .containsExactlyInAnyOrder(
                        "spring-boot-starter-web",
                        "spring-boot-starter-jdbc",
                        "spring-boot-starter-validation",
                        "spring-boot-starter-json",
                        "spring-boot-starter-flyway",
                        "h2");
    }

    @Test
    void keepsIndirectDependenciesTransitive() {
        ParsedSbom sbom = parser.parse(fixture("maven-sbomscope.cdx.json"));

        // A real Maven tree contains all three kinds. If everything came back the same, the
        // graph walk would be silently broken and the column would say nothing.
        assertThat(sbom.components()).extracting(ParsedComponent::scope)
                .contains(DependencyScope.APPLICATION, DependencyScope.DIRECT, DependencyScope.TRANSITIVE);

        assertThat(sbom.components())
                .filteredOn(component -> component.scope() == DependencyScope.TRANSITIVE)
                .isNotEmpty();
    }

    @Test
    void treatsAnNpmRootsDependenciesAsDirect() {
        // npm has no module layer: the root is the package itself, so what it depends on is
        // exactly what package.json declares. This case was already right and must stay so.
        ParsedSbom sbom = parser.parse(fixture("npm-frontend.cdx.json"));

        assertThat(sbom.components())
                .filteredOn(component -> component.scope() == DependencyScope.APPLICATION)
                .hasSize(1)
                .allMatch(ParsedComponent::root);

        assertThat(sbom.components())
                .filteredOn(component -> component.scope() == DependencyScope.DIRECT)
                .extracting(ParsedComponent::name)
                .contains("react", "vite", "typescript");
    }

    @Test
    void collapsesRepeatedDependencyEdges() {
        // Real generators repeat themselves: the same ref listed twice, or the same target
        // twice within one dependsOn. Stored as written, these violate component_dependency's
        // primary key and fail the entire import — an SBOM that simply would not load.
        ParsedSbom sbom = parser.parse(json("""
                {
                  "bomFormat": "CycloneDX",
                  "specVersion": "1.6",
                  "metadata": { "component": { "bom-ref": "root", "name": "app", "version": "1.0.0" }},
                  "components": [
                    { "bom-ref": "a", "name": "lib-a", "version": "1.0.0" },
                    { "bom-ref": "b", "name": "lib-b", "version": "2.0.0" }
                  ],
                  "dependencies": [
                    { "ref": "root", "dependsOn": ["a", "b", "a"] },
                    { "ref": "root", "dependsOn": ["a"] },
                    { "ref": "a", "dependsOn": ["b"] }
                  ]
                }
                """));

        assertThat(sbom.edges()).containsExactly(
                new ParsedSbom.DependencyEdge("root", "a"),
                new ParsedSbom.DependencyEdge("root", "b"),
                new ParsedSbom.DependencyEdge("a", "b"));
    }

    @Test
    void discardsAComponentListedAsItsOwnDependency() {
        // Carries no information, and would turn the scope walk into a self-loop.
        ParsedSbom sbom = parser.parse(json("""
                {
                  "bomFormat": "CycloneDX",
                  "specVersion": "1.6",
                  "metadata": { "component": { "bom-ref": "root", "name": "app", "version": "1.0.0" }},
                  "components": [ { "bom-ref": "a", "name": "lib-a", "version": "1.0.0" } ],
                  "dependencies": [
                    { "ref": "root", "dependsOn": ["a"] },
                    { "ref": "a", "dependsOn": ["a"] }
                  ]
                }
                """));

        assertThat(sbom.edges()).containsExactly(new ParsedSbom.DependencyEdge("root", "a"));
    }

    @Test
    void everyComponentHasAUniqueBomRef() {
        ParsedSbom sbom = parser.parse(fixture("maven-sbomscope.cdx.json"));

        assertThat(sbom.components())
                .extracting(ParsedComponent::bomRef)
                .doesNotHaveDuplicates();
    }

    @Test
    void treatsAFlatSbomAsAllDirect() {
        // No dependency graph at all: reporting everything as transitive would be
        // actively misleading, so the parser reports them as direct instead.
        ParsedSbom sbom = parser.parse(json("""
                {
                  "bomFormat": "CycloneDX",
                  "specVersion": "1.4",
                  "components": [
                    { "bom-ref": "a", "name": "left-pad", "version": "1.0.0" },
                    { "bom-ref": "b", "name": "right-pad", "version": "2.0.0" }
                  ]
                }
                """));

        assertThat(sbom.components()).hasSize(2)
                .allMatch(component -> component.scope() == DependencyScope.DIRECT);
    }

    @Test
    void flattensNestedComponents() {
        ParsedSbom sbom = parser.parse(json("""
                {
                  "bomFormat": "CycloneDX",
                  "specVersion": "1.4",
                  "components": [
                    {
                      "bom-ref": "outer", "name": "outer", "version": "1.0.0",
                      "components": [
                        { "bom-ref": "inner", "name": "inner", "version": "0.1.0" }
                      ]
                    }
                  ]
                }
                """));

        assertThat(sbom.components())
                .extracting(ParsedComponent::name)
                .containsExactlyInAnyOrder("outer", "inner");
    }

    @Test
    void rejectsNonCycloneDxJson() {
        assertThatThrownBy(() -> parser.parse(json("{\"hello\":\"world\"}")))
                .isInstanceOf(InvalidSbomException.class)
                .hasMessageContaining("CycloneDX");
    }

    @Test
    void rejectsSpdxDocuments() {
        assertThatThrownBy(() -> parser.parse(json("""
                { "bomFormat": "SPDX", "specVersion": "2.3" }
                """)))
                .isInstanceOf(InvalidSbomException.class)
                .hasMessageContaining("SPDX");
    }

    @Test
    void rejectsMalformedJsonWithAnActionableMessage() {
        assertThatThrownBy(() -> parser.parse(json("<bom xmlns=\"http://cyclonedx.org\"/>")))
                .isInstanceOf(InvalidSbomException.class)
                .hasMessageContaining("JSON");
    }

    @Test
    void rejectsAnSbomWithNoComponents() {
        assertThatThrownBy(() -> parser.parse(json("""
                { "bomFormat": "CycloneDX", "specVersion": "1.6", "components": [] }
                """)))
                .isInstanceOf(InvalidSbomException.class)
                .hasMessageContaining("no components");
    }

    @Test
    void recognisesKnownSpecVersions() {
        assertThat(CycloneDxParser.isKnownSpecVersion("1.6")).isTrue();
        assertThat(CycloneDxParser.isKnownSpecVersion("0.9")).isFalse();
    }
}
