-- V13 - a sortable form of component version, so the findings table can order by it.
--
-- Additive, as constraint 8 requires: the repository is public and somebody else's data
-- may already be on the other end of every shipped migration.
--
-- Why a column rather than an expression: sorting, filtering and paging all execute in SQL,
-- precisely so the view and the export cannot diverge, and H2 orders version strings lexically
-- - which puts 1.10.0 before 1.9.0. That is not a cosmetic wrong order in a security tool; it
-- is the version in use landing in the wrong place in a list somebody is working down.
--
-- The key is generated by VersionOrder.sortKey, from the same parse the comparator itself uses,
-- so the table cannot disagree with the upgrade advice describing the same versions.
-- VersionSortKeyTest asserts that agreement across the fixture set rather than assuming it.
--
-- NULL where a component names no version, and that is load-bearing: no version is not a version
-- and must not sort as one. Both sort directions put these last.
--
-- Existing rows are left NULL here rather than backfilled in SQL - the key comes from Java, and
-- reimplementing the parse in H2 SQL would be the second interpretation of a version this whole
-- design exists to avoid. ComponentVersionSortBackfill fills them once, after startup.
ALTER TABLE component
    ADD COLUMN version_sort VARCHAR(256);

-- Sorting reads it for every row of the view, and the backfill selects on it being absent.
CREATE INDEX idx_component_version_sort ON component (version_sort);
