/**
 * Reference for the vocabulary this tool unavoidably exposes.
 *
 * <p>SBOMscope shows CVSS scores, GHSA ratings, purls and CycloneDX scopes because those
 * are what the data is. That is fine for someone who already lives in supply-chain
 * security and opaque for everyone else — and the second group is who ends up reading an
 * exported spreadsheet.
 *
 * <p>The column table is the important half: it says where each value comes from, because
 * several of them look interchangeable and are not. A GHSA rating is not the CVSS band, and
 * the published date is the advisory's, not the CVE's.
 */
export function GlossaryPage() {
  return (
    <>
      <div className="page-header">
        <h1>Glossary</h1>
        <p>What the terms mean, and where each column's data comes from.</p>
      </div>

      <section className="panel">
        <h2 className="panel__title">Where the findings come from</h2>
        <p className="panel__hint">
          SBOMscope does not maintain its own vulnerability database. It runs OSV-Scanner
          against a locally-cached copy of the public OSV data and stores what comes back.
        </p>

        <dl className="glossary">
          <dt>SBOM</dt>
          <dd>
            Software Bill of Materials — an inventory of every library your project depends
            on, direct and indirect, with versions. Produced by your build tool, not by
            SBOMscope.
          </dd>

          <dt>CycloneDX</dt>
          <dd>
            The SBOM format SBOMscope reads, in JSON. Generated by the CycloneDX Maven
            plugin or <span className="mono">npm sbom</span>.
          </dd>

          <dt>OSV</dt>
          <dd>
            Open Source Vulnerabilities — a distribution format and public database of
            advisories, aggregating sources including the GitHub Advisory Database. This is
            where every finding here originates.
          </dd>

          <dt>OSV-Scanner</dt>
          <dd>
            Google's scanner, run as an external program. You download and place the binary;
            SBOMscope never fetches it. It matches your components against the offline
            database and reports what it finds. Run with{' '}
            <span className="mono">--offline</span>, so the analysis machine needs no
            internet connection.
          </dd>

          <dt>Offline database</dt>
          <dd>
            A per-ecosystem archive of OSV advisories, downloaded only when you explicitly
            ask. Nothing refreshes on a timer or on startup — which also means results go
            stale until you re-download and re-scan.
          </dd>

          <dt>purl (package URL)</dt>
          <dd>
            A portable identifier for one library at one version, such as{' '}
            <span className="mono">pkg:maven/com.example/lib@1.2.3</span>. SBOMscope caches
            findings against the purl, so a library appearing in five SBOMs is scanned once.
          </dd>
        </dl>
      </section>

      <section className="panel">
        <h2 className="panel__title">Identifiers</h2>
        <p className="panel__hint">
          One vulnerability usually has several names. They are not interchangeable, which
          is why the table shows two of them side by side.
        </p>

        <dl className="glossary">
          <dt>CVE</dt>
          <dd>
            The industry-wide identifier, e.g. <span className="mono">CVE-2024-23689</span>.
            Useful because everyone else uses it too. Links here go to NVD.
          </dd>

          <dt>GHSA</dt>
          <dd>
            A GitHub Advisory Database identifier. Most OSV records for Maven and npm are
            GHSA records, and the CVE is carried as an alias.
          </dd>

          <dt>Advisories without a CVE</dt>
          <dd>
            Around 3% of the Maven set has no CVE at all — GHSA-only records, and{' '}
            <span className="mono">MAL-*</span> entries describing malicious packages. The
            CVE column shows <strong>no CVE</strong> for these. It is a real state, not
            missing data.
          </dd>

          <dt>Aliased advisories</dt>
          <dd>
            When two records describe the same flaw, OSV-Scanner collapses them into one
            finding so you do not see the same problem twice. Occasionally those records
            disagree about severity — see the CVSS vector row below.
          </dd>
        </dl>
      </section>

      <section className="panel">
        <h2 className="panel__title">Severity</h2>
        <dl className="glossary">
          <dt>CVSS</dt>
          <dd>
            Common Vulnerability Scoring System — a 0–10 score derived from a vector
            describing how the flaw is exploited and what it costs you.
          </dd>

          <dt>Why the CVSS version matters</dt>
          <dd>
            v3.1 and v4.0 are different formulas. A v3 7.5 and a v4 7.5 are not the same
            statement and should not be compared or averaged, which is why SBOMscope always
            shows which revision produced a score.
          </dd>

          <dt>Bands</dt>
          <dd>
            Critical 9.0–10.0 · High 7.0–8.9 · Medium 4.0–6.9 · Low 0.1–3.9. These are CVSS's
            own bands, derived from the number.
          </dd>

          <dt>Unscored vs. No vulnerabilities</dt>
          <dd>
            Deliberately separate filters. <strong>Unscored</strong> is a real vulnerability
            whose advisory carries no CVSS score — unknown severity.{' '}
            <strong>No vulnerabilities</strong> is a component with nothing known against it.
            Merging them would let "we don't know how bad this is" read as "this is fine".
          </dd>

          <dt>Never scanned vs. clean</dt>
          <dd>
            SBOMscope records that a component was checked even when nothing was found, so an
            empty result can be told apart from one that was never looked at.
          </dd>
        </dl>
      </section>

      <section className="panel">
        <h2 className="panel__title">What each column shows</h2>
        <p className="panel__hint">
          Everything except the CVE identifier describes the OSV/GHSA advisory record. That
          matters for the two columns most easily mistaken for something else.
        </p>

        <div className="table-scroll">
          <table className="data-table glossary-table">
            <thead>
              <tr>
                <th scope="col">Column</th>
                <th scope="col">Shows</th>
                <th scope="col">Source</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Component</td>
                <td>Library coordinates, linked to its public registry page</td>
                <td>Your SBOM</td>
              </tr>
              <tr>
                <td>Version</td>
                <td>The version you depend on</td>
                <td>Your SBOM</td>
              </tr>
              <tr>
                <td>Scope</td>
                <td>
                  <strong>application</strong> — your own code, including the sibling modules
                  of a multi-module build, which you fix rather than upgrade.{' '}
                  <strong>direct</strong> — declared in your own pom.xml or package.json.{' '}
                  <strong>transitive</strong> — pulled in by something else, so the fix
                  usually means upgrading whatever brought it in.
                </td>
                <td>The SBOM's dependency graph</td>
              </tr>
              <tr>
                <td>OSV ID</td>
                <td>The advisory's own identifier, linked to osv.dev</td>
                <td>OSV record</td>
              </tr>
              <tr>
                <td>GHSA rating</td>
                <td>
                  GitHub's qualitative label: LOW / MODERATE / HIGH / CRITICAL.{' '}
                  <strong>Not the CVSS band</strong> — GitHub calls 6.5 "MODERATE" where CVSS
                  calls it "Medium". Empty for records GitHub did not author.
                </td>
                <td>
                  OSV record, <span className="mono">database_specific</span>
                </td>
              </tr>
              <tr>
                <td>CVE ID</td>
                <td>The CVE alias, linked to NVD</td>
                <td>OSV record aliases</td>
              </tr>
              <tr>
                <td>Severity</td>
                <td>Numeric CVSS score, with its CVSS band beside it</td>
                <td>Computed by OSV-Scanner</td>
              </tr>
              <tr>
                <td>CVSS version</td>
                <td>Which CVSS revision produced the score</td>
                <td>OSV record</td>
              </tr>
              <tr>
                <td>CVSS vector</td>
                <td>
                  The vector behind the score. <strong>Empty when it cannot be attributed</strong>
                  : where aliased advisories disagree, the score shown is the highest among
                  them, so no single vector produces it — printing one anyway would claim a
                  relationship that does not hold.
                </td>
                <td>OSV record</td>
              </tr>
              <tr>
                <td>Fixed in</td>
                <td>
                  The fixing version on <em>your</em> version's branch. An advisory often
                  lists fixes for several coordinates and parallel branches; only the one
                  matching your library is shown.
                </td>
                <td>OSV record</td>
              </tr>
              <tr>
                <td>Published</td>
                <td>
                  When the <strong>advisory</strong> was published — not when the CVE was
                  published by NVD. Those can differ by years. Shown as the UTC date, so it
                  matches the record on osv.dev rather than shifting a day in your own
                  timezone.
                </td>
                <td>OSV record</td>
              </tr>
              <tr>
                <td>Known exploited</td>
                <td>
                  Whether CISA lists this CVE as actively exploited, and since when.{' '}
                  <strong>Empty is not a clearance</strong> — see below. A dash means the finding
                  has no CVE, so a CVE-keyed catalogue cannot be asked about it.
                </td>
                <td>CISA KEV catalogue</td>
              </tr>
              <tr>
                <td>EPSS</td>
                <td>
                  Probability of exploitation in the next 30 days, with its percentile among all
                  scored CVEs. <strong>unscored</strong> means EPSS does not cover that CVE.
                </td>
                <td>FIRST.org EPSS</td>
              </tr>
              <tr>
                <td>Summary</td>
                <td>The advisory's one-line description</td>
                <td>OSV record</td>
              </tr>
              <tr>
                <td>Package URL</td>
                <td>The purl, and the key findings are cached against</td>
                <td>Your SBOM</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section className="panel">
        <h2 className="panel__title">Exploitation signals</h2>
        <p className="panel__hint">
          Severity says how bad a flaw would be. These two say whether anyone is actually
          exploiting it, which is a different question and often the one that decides what you
          do on a Monday morning.
        </p>
        <dl className="glossary">
          <dt>KEV</dt>
          <dd>
            CISA's Known Exploited Vulnerabilities catalogue — a list of flaws confirmed to be
            exploited in the wild. It is a small list: 1,656 entries in total, of which 52 touch
            the Maven advisory set at all. A mark here usually outranks the CVSS score for
            deciding what to fix first.
          </dd>

          <dt>An empty KEV cell is not a clearance</dt>
          <dd>
            <strong>This is the most important line on this page.</strong> KEV is a positive
            list: absence means CISA has not confirmed exploitation, not that a flaw cannot be
            exploited or that anyone has checked. Most exploited vulnerabilities are not in it.
            The column shows <em>not listed</em> rather than “No” for exactly that reason, and
            shows a dash where the finding has no CVE — the catalogue is keyed by CVE, so for
            roughly 3% of Maven advisories the question cannot be asked at all.
          </dd>

          <dt>Ransomware</dt>
          <dd>
            A second mark on a KEV entry CISA has confirmed was used in a ransomware campaign —
            332 of the 1,656. Positive only: its absence means no confirmation, not that
            ransomware is not involved.
          </dd>

          <dt>EPSS</dt>
          <dd>
            Exploit Prediction Scoring System (FIRST.org) — the probability a vulnerability will
            be exploited in the next 30 days. Answers a different question from CVSS, which
            measures impact rather than likelihood, and from KEV, which reports what has already
            been observed. Nearly every CVE has one: 99% of the Maven advisory set.
          </dd>

          <dt>The percentile beside the score</dt>
          <dd>
            Where that score sits among <strong>every CVE EPSS scores worldwide</strong> — about
            354,000 of them — and <strong>not</strong> a rank within your SBOM. It comes verbatim
            from FIRST's file; SBOMscope computes nothing, and the number would be identical on an
            empty SBOM. That distinction matters more than it sounds: a 44% probability sits
            around the 99th percentile globally, because most CVEs score far lower. It is what
            makes the score readable — 0.033 sounds negligible, and “87th percentile” says it is
            worse than most vulnerabilities that exist.
          </dd>

          <dt>There is no official threshold</dt>
          <dd>
            FIRST states plainly that 0.10 is commonly cited and carries no special authority.
            The right cut-off depends on how much remediation you can sustain. SBOMscope
            therefore does not colour or band this column — any line drawn here would be our
            invention wearing FIRST's name.
          </dd>

          <dt>Why a score changed</dt>
          <dd>
            Scores drift a little each day — measured, under 1% of them move at all day to day.
            What moves everything at once is a new <strong>model version</strong>, which happens
            roughly once a year. Two scores from different models are two methodologies rather
            than two states of one vulnerability, which is why Settings shows the model version
            beside the date.
          </dd>

          <dt>Where the data comes from</dt>
          <dd>
            Both are public bulk downloads, fetched only when you ask and never automatically:
            the whole KEV catalogue (about 1.5 MB) and the whole EPSS score file (about 2.4 MB).
            Asking for <em>every</em> exploited vulnerability says nothing about which libraries
            you have, which is why they can be whole files — and why they can be carried onto a
            machine with no network at all.
          </dd>
        </dl>
      </section>
    </>
  );
}
